/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed-variant": "#4a3617",
        "secondary-container": "#f5ebd9",
        "on-tertiary-container": "#92400e",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#b45309",
        "on-surface-variant": "#524330",
        "on-tertiary-fixed-variant": "#78350f",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ded0b8",
        "surface-container": "#f4ebdc",
        "surface-tint": "#b45309",
        "surface": "#fffdfa",
        "surface-container-high": "#ede0cd",
        "inverse-surface": "#332616",
        "on-secondary-fixed": "#241807",
        "on-primary": "#ffffff",
        "on-secondary-container": "#42321c",
        "on-primary-fixed": "#140e04",
        "on-surface": "#1c150b",
        "tertiary-container": "#451a03",
        "outline-variant": "#d8c8b0",
        "secondary": "#6b5636",
        "secondary-fixed": "#f5ebd9",
        "primary-container": "#1c1409",
        "on-secondary-fixed-variant": "#544026",
        "outline": "#8c7352",
        "surface-variant": "#e4d3bc",
        "on-primary-container": "#d4af37",
        "surface-container-low": "#faf4e8",
        "primary-fixed-dim": "#fde68a",
        "surface-container-highest": "#e4d3bc",
        "tertiary-fixed": "#d97706",
        "inverse-primary": "#fde68a",
        "primary-fixed": "#fef3c7",
        "on-secondary": "#ffffff",
        "surface-bright": "#fffdfa",
        "primary": "#140e04",
        "error": "#ba1a1a",
        "background": "#fffdfa",
        "on-tertiary-fixed": "#451a03",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f8f0e3",
        "on-background": "#1c150b",
        "on-error": "#ffffff",
        "surface-dim": "#ded1be",
        "tertiary": "#b45309"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "space-2xl": "3rem",
        "space-4xl": "6rem",
        "container-max": "80rem",
        "gutter-desktop": "2rem",
        "space-5xl": "9rem",
        "space-xl": "2rem",
        "space-2xs": "0.25rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1.25rem",
        "space-md": "1rem",
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "space-3xl": "4.5rem"
      },
      "fontFamily": {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "display-hero": ["Newsreader", "serif"],
        "headline-sm": ["Newsreader", "serif"],
        "headline-lg": ["Newsreader", "serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "body-lead": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Newsreader", "serif"],
        "display-hero-mobile": ["Newsreader", "serif"],
        "caption": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Newsreader", "serif"]
      },
      "fontSize": {
        "body-md": ["1rem", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "headline-md": ["1.75rem", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "display-hero": ["4.5rem", { "lineHeight": "1.08", "letterSpacing": "-0.025em", "fontWeight": "400" }],
        "headline-sm": ["1.375rem", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "500" }],
        "headline-lg": ["2.25rem", { "lineHeight": "1.25", "letterSpacing": "-0.015em", "fontWeight": "400" }],
        "body-sm": ["0.875rem", { "lineHeight": "1.55", "letterSpacing": "0", "fontWeight": "400" }],
        "label-caps": ["0.75rem", { "lineHeight": "1.2", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "body-lead": ["1.25rem", { "lineHeight": "1.65", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-xl": ["3.25rem", { "lineHeight": "1.15", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "display-hero-mobile": ["2.75rem", { "lineHeight": "1.15", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "caption": ["0.75rem", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-xl-mobile": ["2.25rem", { "lineHeight": "1.2", "letterSpacing": "-0.015em", "fontWeight": "400" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
