/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed-variant": "#224838",
        "secondary-container": "#e2ece6",
        "on-tertiary-container": "#b45309",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#d97706",
        "on-surface-variant": "#3d4d44",
        "on-tertiary-fixed-variant": "#78350f",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#c2d4cb",
        "surface-container": "#e8f1ec",
        "surface-tint": "#1b4d3e",
        "surface": "#fbfdfc",
        "surface-container-high": "#dfeae3",
        "inverse-surface": "#233129",
        "on-secondary-fixed": "#0e1f18",
        "on-primary": "#ffffff",
        "on-secondary-container": "#2d3f36",
        "on-primary-fixed": "#041c13",
        "on-surface": "#111c16",
        "tertiary-container": "#451a03",
        "outline-variant": "#cbd5cf",
        "secondary": "#4d6357",
        "secondary-fixed": "#e2ece6",
        "primary-container": "#072b1d",
        "on-secondary-fixed-variant": "#394d42",
        "outline": "#63786e",
        "surface-variant": "#d4e2da",
        "on-primary-container": "#9ec4b0",
        "surface-container-low": "#f2f7f4",
        "primary-fixed-dim": "#a7f3d0",
        "surface-container-highest": "#d4e2da",
        "tertiary-fixed": "#f59e0b",
        "inverse-primary": "#6ee7b7",
        "primary-fixed": "#d1fae5",
        "on-secondary": "#ffffff",
        "surface-bright": "#fbfdfc",
        "primary": "#041c13",
        "error": "#ba1a1a",
        "background": "#fbfdfc",
        "on-tertiary-fixed": "#451a03",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#ebf3ee",
        "on-background": "#111c16",
        "on-error": "#ffffff",
        "surface-dim": "#d2ded7",
        "tertiary": "#051f14"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "space-2xl": "3rem",
        "space-4xl": "6rem",
        "container-max": "80rem",
        "gutter-desktop": "2rem",
        "space-5xl": "9rem",
        "space-xl": "2rem",
        "space-2xs": "0.25rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1.25rem",
        "space-md": "1rem",
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "space-3xl": "4.5rem"
      },
      "fontFamily": {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "display-hero": ["Newsreader", "serif"],
        "headline-sm": ["Newsreader", "serif"],
        "headline-lg": ["Newsreader", "serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "body-lead": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Newsreader", "serif"],
        "display-hero-mobile": ["Newsreader", "serif"],
        "caption": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Newsreader", "serif"]
      },
      "fontSize": {
        "body-md": ["1rem", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "headline-md": ["1.75rem", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "display-hero": ["4.5rem", { "lineHeight": "1.08", "letterSpacing": "-0.025em", "fontWeight": "400" }],
        "headline-sm": ["1.375rem", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "500" }],
        "headline-lg": ["2.25rem", { "lineHeight": "1.25", "letterSpacing": "-0.015em", "fontWeight": "400" }],
        "body-sm": ["0.875rem", { "lineHeight": "1.55", "letterSpacing": "0", "fontWeight": "400" }],
        "label-caps": ["0.75rem", { "lineHeight": "1.2", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "body-lead": ["1.25rem", { "lineHeight": "1.65", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-xl": ["3.25rem", { "lineHeight": "1.15", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "display-hero-mobile": ["2.75rem", { "lineHeight": "1.15", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "caption": ["0.75rem", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-xl-mobile": ["2.25rem", { "lineHeight": "1.2", "letterSpacing": "-0.015em", "fontWeight": "400" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
