/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed-variant": "#394761",
        "secondary-container": "#e6e2dd",
        "on-tertiary-container": "#a5811e",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ecc15a",
        "on-surface-variant": "#44474d",
        "on-tertiary-fixed-variant": "#5a4300",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#cac6c1",
        "surface-container": "#ecedf7",
        "surface-tint": "#515f7a",
        "surface": "#f9f9ff",
        "surface-container-high": "#e6e8f1",
        "inverse-surface": "#2d3038",
        "on-secondary-fixed": "#1d1b19",
        "on-primary": "#ffffff",
        "on-secondary-container": "#666460",
        "on-primary-fixed": "#0c1b33",
        "on-surface": "#191c22",
        "tertiary-container": "#281c00",
        "outline-variant": "#c5c6ce",
        "secondary": "#605e5a",
        "secondary-fixed": "#e6e2dd",
        "primary-container": "#0f1e36",
        "on-secondary-fixed-variant": "#484643",
        "outline": "#75777e",
        "surface-variant": "#e0e2ec",
        "on-primary-container": "#7886a3",
        "surface-container-low": "#f2f3fd",
        "primary-fixed-dim": "#b8c7e6",
        "surface-container-highest": "#e0e2ec",
        "tertiary-fixed": "#ffdf99",
        "inverse-primary": "#b8c7e6",
        "primary-fixed": "#d7e3ff",
        "on-secondary": "#ffffff",
        "surface-bright": "#f9f9ff",
        "primary": "#000412",
        "error": "#ba1a1a",
        "background": "#f9f9ff",
        "on-tertiary-fixed": "#251a00",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eff0fa",
        "on-background": "#191c22",
        "on-error": "#ffffff",
        "surface-dim": "#d8d9e3",
        "tertiary": "#070400"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "space-2xl": "3rem",
        "space-4xl": "6rem",
        "container-max": "80rem",
        "gutter-desktop": "2rem",
        "space-5xl": "9rem",
        "space-xl": "2rem",
        "space-2xs": "0.25rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1.25rem",
        "space-md": "1rem",
        "space-sm": "0.75rem",
        "space-xs": "0.5rem",
        "space-3xl": "4.5rem"
      },
      "fontFamily": {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "display-hero": ["Newsreader", "serif"],
        "headline-sm": ["Newsreader", "serif"],
        "headline-lg": ["Newsreader", "serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "body-lead": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Newsreader", "serif"],
        "display-hero-mobile": ["Newsreader", "serif"],
        "caption": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Newsreader", "serif"]
      },
      "fontSize": {
        "body-md": ["1rem", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "headline-md": ["1.75rem", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "display-hero": ["4.5rem", { "lineHeight": "1.08", "letterSpacing": "-0.025em", "fontWeight": "400" }],
        "headline-sm": ["1.375rem", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "500" }],
        "headline-lg": ["2.25rem", { "lineHeight": "1.25", "letterSpacing": "-0.015em", "fontWeight": "400" }],
        "body-sm": ["0.875rem", { "lineHeight": "1.55", "letterSpacing": "0", "fontWeight": "400" }],
        "label-caps": ["0.75rem", { "lineHeight": "1.2", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "body-lead": ["1.25rem", { "lineHeight": "1.65", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-xl": ["3.25rem", { "lineHeight": "1.15", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "display-hero-mobile": ["2.75rem", { "lineHeight": "1.15", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "caption": ["0.75rem", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-xl-mobile": ["2.25rem", { "lineHeight": "1.2", "letterSpacing": "-0.015em", "fontWeight": "400" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
